from enum import Enum


class ErorrCode(Enum):
    UNKNOWN_ERROR: str = "UNKNOWN_ERROR"
    USER_ALREADY_EXISTS: str = "USER_ALREADY_EXISTS"
    EXECUTOR_ALREADY_EXISTS: str = "EXECUTOR_ALREADY_EXISTS"
    GENRE_DOES_NOT_EXIST: str = "GENRE_DOES_NOT_EXIS"
    USER_EXECUTOR_ALREADY_EXISTS: str = "USER_EXECUTOR_ALREADY_EXISTS"
    ALBUM_ALREADY_EXISTS: str = "ALBUM_ALREADY_EXISTS"


class NotFoundCode(Enum):
    USER_NOT_FOUND: str = "USER_NOT_FOUND"
    ALBUM_NOT_FOUND: str = "ALBUM_NOT_FOUND"
    SONG_NOT_FOUND: str = "SONG_NOF_FOUND"
    SONGS_NOT_FOUND: str = "SONGS_NOT_FOUND"
    EXECUTORS_NOT_FOUND: str = "EXECUTORS_NOT_FOUND"
    EXECUTOR_NOT_FOUND: str = "EXECUTOR_NOT_FOUND"
    SONG_POSITION_NOT_FOUND: str = "SONG_POSITION_NOT_FOUND"
    USER_EXECUTOR_NOT_FOND: str = "USER_EXECUTOR_NOT_FOUND"


class SuccessCode(Enum):
    ADD_EXECUTOR_SUCCESS: str = "ADD_EXECUTOR_SUCCESS"
    ADD_SONGS_SUCCESS: str = "ADD_SONGS_SUCCESS"
    ADD_USER_SUCCESS: str = "CREATE_USER_SUCCESS"
    ADD_AlBUM_SUCCESS: str = "ADD_AlBUM_SUCCESS"
    GET_EXECUTORS_SUCCESS: str = "GET_EXECUTOR_SUCCESS"
    GET_SONGS_SUCCESS: str = "GET_SONGS_SUCCESS"
    GET_SONG_SUCCESS: str = "GET_SONG_SUCCESS"
    GET_ALBUMS_SUCCESS: str = "GET_ALBUMS_SUCCESS"
    UPDATE_PHOTO_SUCCESS: str = "UPDATE_PHOTO_SUCCESS"
    UPDATE_EXECUTOR_COUNTRY_SUCCESS: str = " UPDATE_EXECUTOR_COUNTRY_SUCCESS"
    UPDATE_GENRES_SUCCESS: str = "UPDATE_GENRES_SUCCESS"
    UPDATE_ALBUM_YEAR_SUCCESS: str = "UPDATE_ALBUM_YEAR_SUCCESS"
    UPDATE_ALBUM_TITLE_SUCCESS: str = "UPDATE_ALBUM_TITLE_SUCCESS"
    UPDATE_NAME_SUCCESS: str = "UPDATE_NAME_SUCCESS"
    UPDATE_SONG_TITLE_SUCCESS: str = "UPDATE_SONG_TITLE_SUCCESS"
    DELETE_SONGS_SUCCESS: str = "DELETE_SONGS_SUCCESS"
    DELETE_EXECUTOR_SUCCESS: str = "DELETE_EXECUTOR_SUCCESS"
    DELETE_ALBUM_SUCCES: str = "DELETE_ALBUM_SUCCES"
    SYNC_EXECUTOR_SUCCESS: str = "SYNC_EXECUTOR_SUCCESS"
    DESYNC_EXECUTOR_SUCCESS: str = "DESYNC_EXECUTOR_SUCCESS"
