from enum import Enum


class ErorrCode(Enum):
    UNKNOWN_ERROR: str = "UNKNOWN_ERROR"
    USER_ALREADY_EXISTS: str = "USER_ALREADY_EXISTS"
    EXECUTOR_ALREADY_EXISTS: str = "EXECUTOR_ALREADY_EXISTS"


class NotFoundCode(Enum):
    USER_NOT_FOUND: str = "USER_NOT_FOUND"
    SONGS_NOT_FOUND: str = "SONGS_NOT_FOUND"
    EXECUTORS_NOT_FOUND: str = "EXECUTORS_NOT_FOUND"
    SONG_POSITION_NOT_FOUND: str = "SONG_POSITION_NOT_FOUND"


class SuccessCode(Enum):
    ADD_EXECUTOR_SUCCESS: str = "ADD_EXECUTOR_SUCCESS"
    ADD_SONGS_SUCCESS: str = "ADD_SONGS_SUCCESS"
    ADD_USER_SUCCESS: str = "CREATE_USER_SUCCESS"
    GET_EXECUTORS_SUCCESS: str = "GET_EXECUTOR_SUCCESS"
    GET_SONGS_SUCCESS: str = "GET_SONGS_SUCCESS"
    GET_ALBUMS_SUCCESS: str = "GET_ALBUMS_SUCCESS"
    UPDATE_PHOTO_SUCCESS: str = "UPDATE_PHOTO_SUCCESS"
    UPDATE_SONG_TITLE_SUCCESS: str = "UPDATE_SONG_TITLE_SUCCESS"
    DELETE_SONGS_SUCCESS: str = "DELETE_SONGS_SUCCESS"
